### PR TITLE
removing js and java implementations

### LINKED ISSUE #172: Remove JS and Java implementation
## Which area this feature is related to?

/area library

## Issue Details

After we have officially deprecated the `JS` and `Java` implementations, the next step is to remove them from the project.

**Target date:** 16 May 2023

### LINKED ISSUE #173: Remove Java and JS builds and intergration tests from workflow
## Which area this feature is related to?

/area test-automation

## Issue details

We need to have more clear workflows without any tests and builds for the two deprecated implementations - `Javascript` and `Java`.

**Target date:** 16 May 2023

### PR DESCRIPTION
**Pull request by mike-hoang**
## What does this PR do?

Removes the deprecated javascript and java implementations. An archived version of alizer with the removed implementations are stored here: https://github.com/devfile-resources/alizer 

## Which issue(s) this PR fixes:

fixes #172 and fixes #173

### CODE REVIEW

**Review by thepetk — CHANGES_REQUESTED** [review]
* I think we have also to update the [.github/workflows/release.yaml](https://github.com/redhat-developer/alizer/blob/main/.github/workflows/release.yml) as it builds the java implementation.

* On the testing side (maybe you have already checked that) but IDK if there are any test resources used only from JS and Java.

**Comment by mike-hoang** [comment]
> * I think we have also to update the [.github/workflows/release.yaml](https://github.com/redhat-developer/alizer/blob/main/.github/workflows/release.yml) as it builds the java implementation.

I removed the release workflow as it doesn't seem to be in use at all

> * On the testing side (maybe you have already checked that) but IDK if there are any test resources used only from JS and Java.

There's two projects that don't seem to be used in the tests, but I'll remove them with https://github.com/redhat-developer/alizer/issues/177

- https://github.com/redhat-developer/alizer/tree/main/resources/projects/multiple-dotnet-target-frameworks
- https://github.com/redhat-developer/alizer/tree/main/resources/projects/nodejs-ex-w-devfile

**Review by thepetk — APPROVED** [review]
/lgtm

I'd say before merging we should let everyone know that we are going to remove them permanetly

**Comment by thepetk** [comment]
Maybe we can put a label (e.g on hold) and keep it open. We could also update the issue with the required steps we have discussed? WDYT?

**Comment by mike-hoang** [comment]
Hi @mohitsuman, it looks like the [vscode-tekton](https://github.com/redhat-developer/vscode-tekton) and [intellij-tekton](https://github.com/redhat-developer/intellij-tekton) projects are using the deprecated java and js alizer implementations. Are there any concerns with removing these implementations?

**Comment by mohitsuman** [comment]
@mike-hoang Yes the tekton extensions use alizer to list down the Tekton Hub list. And the logic used there is based on JS implementation. Can you let me know why are we deprecating the JS and Java based implementation. I understand it will be outdated with Go version and it makes sense to update one language, but given the implementations we already have it the past, it should be kept in the project.

**Comment by mike-hoang** [comment]
> Can you let me know why are we deprecating the JS and Java based implementation.

@mohitsuman thanks for the update!
The reason for deprecating is because the alizer project will be onboarded to devfile. Before we move the project, we want the state to be the same which means removing the JS and Java implementations since we will no longer support them

cc @elsony

**Comment by elsony** [comment]
@mohitsuman To clarify: This repo will be used for the go implementation only which we intended to move under the CNCF devfile project. Since the js and Java implementations are no longer under active development, we don't want them to be included as part of the CNCF project. We have moved the js and Java implementation code from the current repo to a separate repo (https://github.com/devfile-resources/alizer) for archiving purposes.

**Comment by mohitsuman** [comment]
@elsony Thanks for the update. I am fine having alizer to have only go implementation and help in solving the devfile use cases. And as we have a separate repo for JS and Java, we can sync how the current go lang version can be used to replace that login in IDE extension (if needed).

So 👍🏼  for having this repo without the non-active implementations.

**Pull request merged**
