### PR TITLE
feat: retrieve project name when doing component detection (#96)

### LINKED ISSUE #96: add project name detection
One of the information that tools are going to require from users is the project name.
Tooling will usually ask users to provide a name. But It would be nice if Alizer provides project name detection that could be used as the default project name.

It would be nice if Alizer provides a function that detects the project name from the information (source code) available. (maybe something like `recognizer.SuggestName(path)`)

Most of the languages already have a place that contains the project name.
- JavaScript: `name` field in `package.json`
- Java (Maven): `artifactId` in `pom.xml`

If Alizer can't detect the project name or the language ecosystem doesn't have a standard way to define a name fallback would be the directory name. 

the related odo issue https://github.com/redhat-developer/odo/issues/5847

### PR DESCRIPTION
**Pull request by lstocchi**
it resolves #96

### CODE REVIEW

**Review by jeffmaury — COMMENTED** [review]
LGTM but I have the feeling this is a breaking change because of the package move so I think major version should be bumped.
WDYT ?

**Comment by kadel** [comment]
Did a few tests, and it looks good.


> LGTM but I have the feeling this is a breaking change because of the package move so I think major version should be bumped.

The package that got renamed is not something that would be typically consumed by projects using this library. bumping a major version might not be necessary.
But that package has exported structs so technically someone could import it. If we want to be nice and do the right thing next release should bump major version.

**Comment by kadel** [comment]
I just noticed that there is only one official Alizer release and that is 0.1.0, so I'm not sure if we want to worry about breaking changes at this point. It is still early in the development and I assume that there will be a lot more changes like this before 1.0 is reached.

**Review by kadel — APPROVED** [review]

**Comment by lstocchi** [comment]
Yeah we talked about it privately. We agree with you, no need to worry for the moment even because 0.1.0 doesn't contain the `Go` implementation (only Java) so officially there is nothing to break.

**Pull request merged**
